language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
dist: xenial
addons:
  homebrew:
    update: true
    packages:
    - eigen
    - qt
  apt:
    packages:
    - qt5-default
    - libqt5opengl5-dev
    - libeigen3-dev
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv global 3.7.1; fi
script:
- cmake -DSEQUENTIAL_LINE_SEARCH_BUILD_COMMAND_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_VISUAL_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PHOTO_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PYTHON_BINDING=OFF . && make
- cmake -DSEQUENTIAL_LINE_SEARCH_BUILD_COMMAND_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_VISUAL_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PHOTO_DEMOS=OFF -DSEQUENTIAL_LINE_SEARCH_BUILD_PYTHON_BINDING=ON . && make
- cmake -DSEQUENTIAL_LINE_SEARCH_BUILD_COMMAND_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_VISUAL_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_PHOTO_DEMOS=ON -DSEQUENTIAL_LINE_SEARCH_BUILD_PYTHON_BINDING=OFF . && make
after_success:
- make test
